config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs

  authenticated :user do
  	root "docs#index",as: "authenticated_root"
  end
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
	before_action :find_doc, only: [:show,:edit,:update,:destroy]

	def index
		@docs=Doc.where(user_id: current_user)

	end

	def show
		
	end

	def new 
		@doc=current_user.docs.build
	end 

	def create
		@doc=current_user.docs.build(doc_params)
		if @doc.save
			redirect_to @doc
		else
			render 'new'
		end

	end

	def edit
	end

	def update
		if @doc.update(doc_params)
			redirect_to @doc
		else
			render 'edit'
		end
	end

	def destroy
		@doc.destroy
		 redirect_to docs_path
	end

	private

		def find_doc
			@doc=Doc.find(params[:id])
		end

		def doc_params
			params.require(:doc).permit(:title,:content)
		end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|

 = f.input :title
 = f.input :content
 = f.button :submit

app/views/docs/edit.html.haml
%h1 Fix Document

= render 'form'
= link_to "cancel",doc_path

app/views/docs/index.html.haml
- @docs.each do |doc|
 %h2= link_to doc.title, doc
 %p= time_ago_in_words(doc.created_at)
 %p= truncate(doc.content, length:50)

 = link_to "Create doc",new_doc_path
 = link_to "Log out",destroy_user_session_path, method: :delete

app/views/docs/new.html.haml
%h1 New Form 

= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%p= @doc.content
= link_to "all doc",docs_path
= link_to "Fix Doc",edit_doc_path(@doc)
= link_to "Trash it", doc_path(@doc) ,method: :delete,data: {confirm: "are you sure ?"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cabinet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	 <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.haml
%h1 voila new text


= link_to "Log in",new_user_session_path
= link_to "sign up ",new_user_registration_path